### ISSUE TITLE
Is there no way to use database columns from the structure? To get type-save

### ISSUE THREAD

**Issue by FlymeDllVa** [leporo/sqlf#6]
Is there no way to use database columns from the structure? To get type-save

**Comment by leporo** [comment]
I'm sorry for really delayed response - for some reason I got no notifications about your issue.

Unfortunately, there is no real way to get type-safe as `sqlf` has no idea on database schema/structure.
It just helps to build an SQL statement in run-time and map arguments to placeholders.

There is a `Bind` method to map annotated structure fields to table columns.

```
type Row struct {
     Field string `db:"column"`
}

var row Row

err := sqlf.From("table").Bind(&row).QueryRowAndClose(context.TODO(), db)
```

As in most cases input structure format differs from the ones used to retrieve data from database (*string vs sql.NullString) there is no helper function for binding a structure for insert/update.
