### ISSUE TITLE
how about support insert batch

### ISSUE THREAD

**Issue by KennyChenFight** [leporo/sqlf#7]
as title

**Comment by leporo** [comment]
I had plans to add a support for multi-row insert statements like this one:

`INSERT INTO table (column1, column2) VALUES (1, "one"), (2, "two)`

but never really needed it. Do you need it?

The effect really depends on database driver. Can you please clarify what database driver do you use?

**Comment by KennyChenFight** [comment]
> I had plans to add a support for multi-row insert statements like this one:
> 
> `INSERT INTO table (column1, column2) VALUES (1, "one"), (2, "two)`
> 
> but never really needed it. Do you need it?
> 
> The effect really depends on database driver. Can you please clarify what database driver do you use?

I use postgres driver, but i think batch insert is much better than single insert when insert many rows

**Comment by Sly-Little-Fox** [comment]
I'm going to try and implement it.
